services:
  web:
    build: .
    restart: unless-stopped
    depends_on:
      - redis
    networks:
      - default
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.hallo.rule=Host(`hallo.${DOMAIN}`)
      - traefik.http.routers.hallo.entrypoints=web
      - traefik.http.services.hallo.loadbalancer.server.port=5001

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis-daten:/data

volumes:
  redis-daten:

networks:
  proxy:
    external: true